name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: [master]
  workflow_dispatch:

# Cancel any in-progress job or run
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      FORCE_COLOR: true
      UV_SYSTEM_PYTHON: 1
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Set up uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv pip install --group=docs --editable .

      - name: Build documentation
        run: |
          make -C docs clean
          make -C docs html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
