name: Python tests

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]  # macos-latest
        python-version: ["3.9", "3.10", "3.11"]

    runs-on: ${{ matrix.platform }}

    env:
      FORCE_COLOR: true

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt
        pip install .

    - name: Test with pytest
      run: |
        pytest --cov --cov-report=xml --cov-config=setup.cfg --verbose

    - name: Upload coverage report
      if: ${{ matrix.platform == 'ubuntu-latest' && matrix.python-version == 3.9 }}
      uses: codecov/codecov-action@v1
      with:
        token: a58a0c62-fb11-4429-977b-65bec01ecb44
        file: ./coverage.xml