name: Python tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]  # macos-latest disabled because of lightgbm fail
        python-version: ["3.9", "3.10", "3.11"]  # lspopt failure on "3.12", see PR187

    runs-on: ${{ matrix.platform }}

    env:
      FORCE_COLOR: true

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[test]"

    - name: Test with pytest
      run: |
        pytest --cov --cov-report=xml --verbose

    - name: Upload coverage report
      if: ${{ matrix.platform == 'ubuntu-latest' && matrix.python-version == 3.9 }}
      uses: codecov/codecov-action@v4
      with:
        token: a58a0c62-fb11-4429-977b-65bec01ecb44
        file: ./coverage.xml